site_name: My Docs
theme:
  name: material
  features:
    - mermaid
nav:
  - 'Strona główna': 'index.md'
  - 'Matematyka': 'matematyka.md'
  - 'Teoria Grup': 'teoria_grup.md'
  - 'Rzut ukośny': 'rzut_ukosny.md'
  - 'Topologia i Metryki': 'metryki_topologia.md'
  - 'Rysowanie Grafik': 'rysowanie_grafik.md'
  - 'Demo': 'demo.md'
  - 'Animacja 2': 'anim_2.html'
  - 'Dyfrakcja': 'dyfrakcja.html'
  - 'Siła Lorentza': 'sila_lotentza.html'
  - 'Sprężystość': 'sprezyny.html'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs_matplotlib